<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/default/files/composer';

return array(
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'GuzzleHttp\\Stream\\' => array($vendorDir . '/guzzlehttp/streams/src'),
    'GuzzleHttp\\Ring\\' => array($vendorDir . '/guzzlehttp/ringphp/src'),
    'GuzzleHttp\\Command\\Guzzle\\' => array($vendorDir . '/guzzlehttp/guzzle-services/src'),
    'GuzzleHttp\\Command\\' => array($vendorDir . '/guzzlehttp/command/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Drupalway\\NovaPoshta\\Tests\\' => array($vendorDir . '/drupalway/nova-poshta-guzzle/test'),
    'Drupalway\\NovaPoshta\\' => array($vendorDir . '/drupalway/nova-poshta-guzzle/src'),
);
