<?php
/**
 * Implements hook_init().
 */
function update_cart_init() {
  drupal_add_library('system', 'ui.spinner');
}

/**
 * Implements hook_form_alter().
 */
function update_cart_form_alter(&$form, &$form_state, $form_id) {
  // Add to cart.
  if (strpos($form_id, 'commerce_cart_add_to_cart_form_') !== FALSE) {
    $form['quantity']['#title'] = 'Кол-во:';
    $form['submit']['#value'] = 'Добавить в корзину';
  }
  // Cart page.
  if (strpos($form_id, 'views_form_commerce_cart_form_') !== FALSE) {
    $form['actions']['submit']['#value'] = 'Обновить корзину';
    $form['actions']['submit']['#attributes']['class'][] = 'update_cart_btn';
    $form['actions']['checkout']['#value'] = 'Оформить заказ';
    $form['actions']['checkout']['#attributes']['class'][] = 'checkout_btn';
    if(!empty($form['edit_quantity'])) {
      foreach ($form['edit_quantity'] as $key => $edit_quantity) {
        if (is_array($edit_quantity)) {
          $form['edit_quantity'][$key]['#attributes']['readonly'] = 'readonly';
        }
      }
    }
  }
  // Checkout page.
  if($form_id == 'commerce_checkout_form_checkout'){
    $form['buttons']['cancel']['#value'] = 'Изменить заказ';
    $form['buttons']['cancel']['#prefix'] = '';
    $form['buttons']['cancel']['#attributes']['class'] = array('chekout-go-back');
    $form['buttons']['continue']['#suffix'] =
      '<span class="checkout-processing element-invisible"><div class="throbber">&nbsp;</div></span>';
    $form['customer_profile_billing']['#title'] = 'Контактные данные';
    $form['customer_profile_billing']['required']['#markup'] = '<p class="required-description">* - поля обязательные для заполнения</p><div class="clear"></div>';
    $form['customer_profile_billing']['required']['#weight'] = -1;
    $form['#attributes']['class'] = array('form-checkout');
    array_unshift($form['buttons']['continue']['#submit'], 'update_cart_checkout_form_submit_save_email');
  }
  // Review page.
  if($form_id == 'commerce_checkout_form_review'){
    $form['#attributes']['class'] = array('form-checkout-review');
    $form['buttons']['continue']['#suffix'] =
      '<span class="checkout-processing element-invisible"><div class="throbber">&nbsp;</div></span>';
    $form['buttons']['back']['#value'] = 'Изменить контактные данные';
    $form['buttons']['back']['#prefix'] = '';
    $form['buttons']['back']['#attributes']['class'] = array('chekout-go-back');
    $form['cart_contents']['#title'] = 'Заказ';
  }
  // Contact form.
  if($form_id == 'webform_client_form_11'){
    $form['#after_build'][] = 'update_cart_captcha_pre_render';
    $form['required']['#markup'] = '<p class="required-description absolute">* - поля обязательные для заполнения</p>';
    foreach(array('name', 'email', 'phone', 'comment') as $field_name) {
      $form['submitted'][$field_name]['#prefix'] = '<div class="field-wrap ' . $field_name . '">';
      $form['submitted'][$field_name]['#suffix'] = '</div>';
    }
  }
  // Search block.
  if ($form_id == 'search_block_form') {
    $form['actions']['submit']['#prefix'] = '<button type="submit" class="form-submit-btn">';
    $form['actions']['submit']['#suffix'] = '</button>';
    $form['actions']['submit']['#attributes'] = array( 'style' => array( 'display: none' ));
  }
  // Search page
  if ($form_id == 'search_form') {
    $form['basic']['submit']['#prefix'] = '<button type="submit" class="form-submit-btn">';
    $form['basic']['submit']['#suffix'] = '</button>';
    $form['basic']['submit']['#attributes'] = array( 'style' => array( 'display: none' ));
    $form['basic']['keys']['#title'] = '';
  }
}

/**
 * Implements hook_captcha().
 */
function update_cart_captcha_pre_render($form, &$form_state) {
  $form['captcha']['captcha_widgets']['captcha_response']['#title'] = 'Защитный код';
  return $form;
}

/**
 * Form submit handler for commerce_checkout_form_checkout().
 */
function update_cart_checkout_form_submit_save_email($form, &$form_state){
  if(!empty($form_state['values']['customer_profile_billing']['field_email'][LANGUAGE_NONE][0]['value'])) {
    $form_state['order']->mail = $form_state['values']['customer_profile_billing']['field_email'][LANGUAGE_NONE][0]['value'];
  }
}
/**
 * Implements hook_menu_alter().
 */
function update_cart_menu_alter(&$items) {
  $items['cart']['title'] = 'Корзина';
  $items['search']['title'] = 'Поиск';
  $items['search/node']['title'] = 'Контент';
  $items['search/node/%menu_tail']['title'] = 'Контент';
}

/**
 * Implements hook_commerce_price_formatted_components_alter().
 */
function update_cart_commerce_price_formatted_components_alter(&$components, $price, $entity) {
  $pieces = explode('/',current_path());
  if(!isset($components['tax|ch_vat']) && $pieces[0] == 'checkout'){
    $components['commerce_price_formatted_amount']['title'] = 'Общая сумма';
  }
}
